// Babykalender data — week 0-26 + maand 7-24
// Elk item heeft een label, onderwerpen, en link naar 24baby.nl

export const BABY_WEEKS = [
  { week: 0, label: '0 weken', topics: ['De eerste ontmoeting', 'Het gouden uur', 'Herstellen en wennen'], url: 'https://www.24baby.nl/baby-kalender/baby-0-weken-oud/' },
  { week: 1, label: '1 week', topics: ['Babyblues', 'Reflexen', 'Opstartproblemen'], url: 'https://www.24baby.nl/baby-kalender/baby-1-week-oud/' },
  { week: 2, label: '2 weken', topics: ['De wereld ontdekken', 'Terug op het geboortegewicht', 'Nieuwe kwalen'], url: 'https://www.24baby.nl/baby-kalender/baby-2-weken-oud/' },
  { week: 3, label: '3 weken', topics: ['Tummy time', 'Babyacne', 'Kraambedoefeningen'], url: 'https://www.24baby.nl/baby-kalender/baby-3-weken-oud/' },
  { week: 4, label: '4 weken', topics: ['Geheime taal', 'Vreemde geluiden', 'Clusteren en tepelleed'], url: 'https://www.24baby.nl/baby-kalender/baby-4-weken-oud/' },
  { week: 5, label: '5 weken', topics: ['De eerste echte lach', 'Veilig slapen', 'Seks met je partner'], url: 'https://www.24baby.nl/baby-kalender/baby-5-weken-oud/' },
  { week: 6, label: '6 weken', topics: ['Babygeluiden', 'Darmkrampjes', 'De nacontrole'], url: 'https://www.24baby.nl/baby-kalender/baby-6-weken-oud/' },
  { week: 7, label: '7 weken', topics: ['Slapen, slapen en slapen', 'Sabbelen op duim of fopspeen', 'Nog steeds een donkere wolk?'], url: 'https://www.24baby.nl/baby-kalender/baby-7-weken-oud/' },
  { week: 8, label: '8 weken', topics: ['Vaccinaties', 'De eerste prikken', 'Veel plezier met je baby'], url: 'https://www.24baby.nl/baby-kalender/baby-8-weken-oud/' },
  { week: 9, label: '9 weken', topics: ['De wereld om je heen', 'Kraampjes en groeilijntjes', 'Relatie na de baby'], url: 'https://www.24baby.nl/baby-kalender/baby-9-weken-oud/' },
  { week: 10, label: '10 weken', topics: ['Brabbelen en kirren', 'Tranen met tuiten', 'Lekker in bad'], url: 'https://www.24baby.nl/baby-kalender/baby-10-weken-oud/' },
  { week: 11, label: '11 weken', topics: ['Grijpen en pakken', 'Speelgoed voor je baby', 'Handig: een draagzak'], url: 'https://www.24baby.nl/baby-kalender/baby-11-weken-oud/' },
  { week: 12, label: '12 weken', topics: ['3 maanden!', 'Vast ritme', 'De juiste oppas'], url: 'https://www.24baby.nl/baby-kalender/baby-12-weken-oud/' },
  { week: 13, label: '13 weken', topics: ['Haarverlies bij je baby en jou', 'Een hoofdhuid met berg', 'Jouw lichaam na de bevalling'], url: 'https://www.24baby.nl/baby-kalender/baby-13-weken-oud/' },
  { week: 14, label: '14 weken', topics: ['De work-out van je baby', 'Luierproblemen', 'Tijd voor je partner'], url: 'https://www.24baby.nl/baby-kalender/baby-14-weken-oud/' },
  { week: 15, label: '15 weken', topics: ['Je baby wordt socialer', 'Weer aan het werk', 'Oppas gezocht'], url: 'https://www.24baby.nl/baby-kalender/baby-15-weken-oud/' },
  { week: 16, label: '16 weken', topics: ['De eerste hapjes', 'Tijdelijke slaapproblemen', 'Een nieuw seksleven'], url: 'https://www.24baby.nl/baby-kalender/baby-16-weken-oud/' },
  { week: 17, label: '17 weken', topics: ['Lief gebrabbel', 'Oefenen met rollen', 'Borstvoeding en alcohol'], url: 'https://www.24baby.nl/baby-kalender/baby-17-weken-oud/' },
  { week: 18, label: '18 weken', topics: ['Schateren van het lachen', 'Smakelijke teentjes', 'Oude en nieuwe klachten'], url: 'https://www.24baby.nl/baby-kalender/baby-18-weken-oud/' },
  { week: 19, label: '19 weken', topics: ['Babycommunicatie', 'Weer een prik', 'Aandacht verdelen'], url: 'https://www.24baby.nl/baby-kalender/baby-19-weken-oud/' },
  { week: 20, label: '20 weken', topics: ['Groeien als kool', 'Besmettelijke kinderziektes', 'Voedingsvragen'], url: 'https://www.24baby.nl/baby-kalender/baby-20-weken-oud/' },
  { week: 21, label: '21 weken', topics: ['Een eigen persoonlijkheid', 'Naar de tandarts', 'Leuke uitstapjes'], url: 'https://www.24baby.nl/baby-kalender/baby-21-weken-oud/' },
  { week: 22, label: '22 weken', topics: ['Starten met bijvoeding', 'Tandjes!', 'Lachen met papa en mama'], url: 'https://www.24baby.nl/baby-kalender/baby-22-weken-oud/' },
  { week: 23, label: '23 weken', topics: ['Twee handjes', 'Halfjaarcontrole', 'Reizen met je baby'], url: 'https://www.24baby.nl/baby-kalender/baby-23-weken-oud/' },
  { week: 24, label: '24 weken', topics: ['Ogen, oren en meer', 'Ritme en regelmaat', 'Anticonceptie revisited'], url: 'https://www.24baby.nl/baby-kalender/baby-24-weken-oud/' },
  { week: 25, label: '25 weken', topics: ['Zitten en bewegen', 'Verlatingsangst', 'Het eigen maken van eten'], url: 'https://www.24baby.nl/baby-kalender/baby-25-weken-oud/' },
  { week: 26, label: '26 weken', topics: ['Half jaar!', 'Vaste voeding uitbreiden', 'Samen spelen'], url: 'https://www.24baby.nl/baby-kalender/baby-26-weken-oud/' },
]

export const BABY_MONTHS = [
  { month: 7, label: '7 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-7-maanden-oud/' },
  { month: 8, label: '8 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-8-maanden-oud/' },
  { month: 9, label: '9 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-9-maanden-oud/' },
  { month: 10, label: '10 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-10-maanden-oud/' },
  { month: 11, label: '11 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-11-maanden-oud/' },
  { month: 12, label: '12 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-12-maanden-oud/' },
  { month: 13, label: '13 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-13-maanden-oud/' },
  { month: 14, label: '14 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-14-maanden-oud/' },
  { month: 15, label: '15 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-15-maanden-oud/' },
  { month: 16, label: '16 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-16-maanden-oud/' },
  { month: 17, label: '17 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-17-maanden-oud/' },
  { month: 18, label: '18 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-18-maanden-oud/' },
  { month: 19, label: '19 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-19-maanden-oud/' },
  { month: 20, label: '20 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-20-maanden-oud/' },
  { month: 21, label: '21 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-21-maanden-oud/' },
  { month: 22, label: '22 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-22-maanden-oud/' },
  { month: 23, label: '23 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-23-maanden-oud/' },
  { month: 24, label: '24 maanden', url: 'https://www.24baby.nl/baby-kalender/baby-24-maanden-oud/' },
]
